/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.pe.vista;

import java.awt.BorderLayout;
import javax.swing.GroupLayout;
import pe.edu.pe.vista.cliente.ListarCliente;

/**
 *
 * @author REDES-PC32
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        panel_Izquierdo = new javax.swing.JPanel();
        lb_titulo_principal = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btn_inicio = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        panel_superior = new javax.swing.JPanel();
        lb_titulo_superior = new javax.swing.JLabel();
        panel_central = new javax.swing.JPanel();
        lb_bienvenida = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(761, 520));

        panelPrincipal.setBackground(new java.awt.Color(239, 239, 239));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Izquierdo.setBackground(new java.awt.Color(246, 183, 32));

        lb_titulo_principal.setBackground(new java.awt.Color(246, 183, 32));
        lb_titulo_principal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo_principal.setText("Residencias UPeU");

        separador.setBackground(new java.awt.Color(15, 53, 92));
        separador.setForeground(new java.awt.Color(15, 53, 92));

        btn_inicio.setBackground(new java.awt.Color(246, 183, 32));
        btn_inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/inicio.png"))); // NOI18N
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(null);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_clientes.setBackground(new java.awt.Color(246, 183, 32));
        btn_clientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/clientes.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.setBorder(null);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_IzquierdoLayout = new javax.swing.GroupLayout(panel_Izquierdo);
        panel_Izquierdo.setLayout(panel_IzquierdoLayout);
        panel_IzquierdoLayout.setHorizontalGroup(
            panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IzquierdoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_titulo_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(separador))
                    .addGroup(panel_IzquierdoLayout.createSequentialGroup()
                        .addGroup(panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_inicio)
                            .addComponent(btn_clientes))
                        .addGap(68, 68, 68)))
                .addGap(33, 33, 33))
        );
        panel_IzquierdoLayout.setVerticalGroup(
            panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IzquierdoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb_titulo_principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_inicio)
                .addGap(18, 18, 18)
                .addComponent(btn_clientes)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_Izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 520));

        panel_superior.setBackground(new java.awt.Color(15, 53, 92));

        lb_titulo_superior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_titulo_superior.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/logo.jpg"))); // NOI18N
        lb_titulo_superior.setText("Sistema de Gestión de Residencias");

        javax.swing.GroupLayout panel_superiorLayout = new javax.swing.GroupLayout(panel_superior);
        panel_superior.setLayout(panel_superiorLayout);
        panel_superiorLayout.setHorizontalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superiorLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lb_titulo_superior)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panel_superiorLayout.setVerticalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_titulo_superior)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 550, 70));

        panel_central.setBackground(new java.awt.Color(239, 239, 239));

        lb_bienvenida.setBackground(new java.awt.Color(239, 239, 239));
        lb_bienvenida.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lb_bienvenida.setText("Bienvenido al Sistema...");

        javax.swing.GroupLayout panel_centralLayout = new javax.swing.GroupLayout(panel_central);
        panel_central.setLayout(panel_centralLayout);
        panel_centralLayout.setHorizontalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_centralLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(lb_bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        panel_centralLayout.setVerticalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centralLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lb_bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        panelPrincipal.add(panel_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 550, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        panel_central.removeAll(); // eliminar contenido dinámico
        // mostrar solo el mensaje original
        panel_central.setLayout(new GroupLayout(panel_central));
        lb_bienvenida.setVisible(true);
        panel_central.add(lb_bienvenida); // vuelve a añadir el JLabel si es necesario
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        ListarCliente lista = new ListarCliente();
        lb_bienvenida.setVisible(false);
        lista.setVisible(true);
        lista.setSize(550, 450);
        lista.setLocation(0, 0);
        panel_central.removeAll();
        panel_central.add(lista, BorderLayout.CENTER);
        panel_central.revalidate();
        panel_central.repaint();
    }//GEN-LAST:event_btn_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bienvenida;
    private javax.swing.JLabel lb_titulo_principal;
    private javax.swing.JLabel lb_titulo_superior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panel_Izquierdo;
    private javax.swing.JPanel panel_central;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
