
package pe.edu.pe.vista.cliente;

import javax.swing.JOptionPane;
import pe.edu.pe.implementacion.ClienteDaoImpl;
import pe.edu.pe.interfaces.IClienteDao;
import pe.edu.pe.modelo.Cliente;

/** @author Jhan Arly **/
public class EditarCliente extends javax.swing.JFrame {
    int idcliente;
    public EditarCliente(int idcliente) {
        this.idcliente = idcliente;
        initComponents();
        BuscarCliente(idcliente);
    }
    
    public void BuscarCliente(int idcliente) {

        IClienteDao cDAO = new ClienteDaoImpl();
        Cliente c = cDAO.buscarPorId(idcliente);
        try {
            txt_nombres_editar.setText(c.getNombre());
            txt_apellidos_editar.setText(c.getApellidos());
            txt_dni_editar.setText(c.getDni());
            txt_email_editar.setText(c.getEmail());
       // Seleccionar el radio button correcto según el género
        if ("M".equalsIgnoreCase(c.getGenero())) {
            rb_m_editar.setSelected(true);
        } else if ("F".equalsIgnoreCase(c.getGenero())) {
            rb_f_editar.setSelected(true);
        } else {
            genero_editar.clearSelection();
        }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos.", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero_editar = new javax.swing.ButtonGroup();
        Formulario_editar = new javax.swing.JPanel();
        lb_nombres_editar = new javax.swing.JLabel();
        lb_apellidos_editar = new javax.swing.JLabel();
        lb_dni_editar = new javax.swing.JLabel();
        lb_email_editar = new javax.swing.JLabel();
        lb_genero_editar = new javax.swing.JLabel();
        txt_nombres_editar = new javax.swing.JTextField();
        txt_apellidos_editar = new javax.swing.JTextField();
        txt_email_editar = new javax.swing.JTextField();
        txt_dni_editar = new javax.swing.JTextField();
        rb_m_editar = new javax.swing.JRadioButton();
        rb_f_editar = new javax.swing.JRadioButton();
        btn_cancelar_editar = new javax.swing.JButton();
        btn_actualizar_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Formulario_editar.setBackground(new java.awt.Color(239, 239, 239));
        Formulario_editar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Editar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(15, 53, 92))); // NOI18N

        lb_nombres_editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_nombres_editar.setText("Nombres      :");

        lb_apellidos_editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_apellidos_editar.setText("Apellidos      :");

        lb_dni_editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_dni_editar.setText("DNI               :");

        lb_email_editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_email_editar.setText("Email            :");

        lb_genero_editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_genero_editar.setText("Género         :");

        txt_nombres_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombres_editarActionPerformed(evt);
            }
        });

        txt_apellidos_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidos_editarActionPerformed(evt);
            }
        });

        genero_editar.add(rb_m_editar);
        rb_m_editar.setText("M");

        genero_editar.add(rb_f_editar);
        rb_f_editar.setText("F");

        btn_cancelar_editar.setBackground(new java.awt.Color(246, 183, 32));
        btn_cancelar_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cancelar_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar_editar.setText("Cancelar");
        btn_cancelar_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_editarActionPerformed(evt);
            }
        });

        btn_actualizar_editar.setBackground(new java.awt.Color(15, 53, 92));
        btn_actualizar_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_actualizar_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar_editar.setText("Actualizar");
        btn_actualizar_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Formulario_editarLayout = new javax.swing.GroupLayout(Formulario_editar);
        Formulario_editar.setLayout(Formulario_editarLayout);
        Formulario_editarLayout.setHorizontalGroup(
            Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Formulario_editarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombres_editar)
                    .addComponent(lb_apellidos_editar)
                    .addComponent(lb_dni_editar)
                    .addComponent(lb_email_editar)
                    .addComponent(lb_genero_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_apellidos_editar)
                        .addComponent(txt_nombres_editar)
                        .addComponent(txt_dni_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Formulario_editarLayout.createSequentialGroup()
                        .addComponent(rb_m_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_f_editar)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Formulario_editarLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btn_actualizar_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar_editar)
                .addGap(125, 125, 125))
        );
        Formulario_editarLayout.setVerticalGroup(
            Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Formulario_editarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombres_editar)
                    .addComponent(txt_nombres_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_apellidos_editar)
                    .addComponent(txt_apellidos_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dni_editar)
                    .addComponent(txt_dni_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email_editar)
                    .addComponent(txt_email_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_genero_editar)
                    .addComponent(rb_m_editar)
                    .addComponent(rb_f_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(Formulario_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar_editar)
                    .addComponent(btn_actualizar_editar))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Formulario_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Formulario_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombres_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombres_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombres_editarActionPerformed

    private void txt_apellidos_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidos_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidos_editarActionPerformed

    private void btn_cancelar_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_editarActionPerformed
         this.setVisible(false);
        
    }//GEN-LAST:event_btn_cancelar_editarActionPerformed

    private void btn_actualizar_editarActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = txt_nombres_editar.getText();
        String apellidos = txt_apellidos_editar.getText();
        String dni = txt_dni_editar.getText();
        String email = txt_email_editar.getText();
        String genero = rb_m_editar.isSelected() ? "M" : rb_f_editar.isSelected() ? "F" : "";

        Cliente c = new Cliente();
        c.setIdcliente(this.idcliente); // se usa la variable interna
        c.setNombre(nombre);
        c.setApellidos(apellidos);
        c.setDni(dni);
        c.setEmail(email);
        c.setGenero(genero);

        IClienteDao cDAO = new ClienteDaoImpl();
        boolean actualizado = cDAO.actualizar(c);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
            this.dispose(); // cerrar ventana si quieres
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el cliente.");
        }

    }//GEN-LAST:event_btn_actualizar_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Formulario_editar;
    private javax.swing.JButton btn_actualizar_editar;
    private javax.swing.JButton btn_cancelar_editar;
    private javax.swing.ButtonGroup genero_editar;
    private javax.swing.JLabel lb_apellidos_editar;
    private javax.swing.JLabel lb_dni_editar;
    private javax.swing.JLabel lb_email_editar;
    private javax.swing.JLabel lb_genero_editar;
    private javax.swing.JLabel lb_nombres_editar;
    private javax.swing.JRadioButton rb_f_editar;
    private javax.swing.JRadioButton rb_m_editar;
    private javax.swing.JTextField txt_apellidos_editar;
    private javax.swing.JTextField txt_dni_editar;
    private javax.swing.JTextField txt_email_editar;
    private javax.swing.JTextField txt_nombres_editar;
    // End of variables declaration//GEN-END:variables
}
