package pe.edu.pe.vista.cliente;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.pe.implementacion.ClienteDaoImpl;
import pe.edu.pe.interfaces.IClienteDao;
import pe.edu.pe.modelo.Cliente;

/**
 * @author Jhan Arly *
 */
public class ListarCliente extends javax.swing.JPanel {

    IClienteDao CDao = new ClienteDaoImpl();
    Cliente c = new Cliente();
    
    public ListarCliente() {
        initComponents();
        cargarClientes();
    }
    public void cargarClientes() {
        List<Cliente> lista = CDao.listarClientes();

        DefaultTableModel tableModel = (DefaultTableModel) tbl_clientes.getModel();
        tableModel.setNumRows(0);
        for (Cliente c : lista) {
            String genero;
            if (c.getGenero().equals("M")) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            Object[] rowData
                    = {
                        c.getIdcliente(),
                        c.getNombre(),
                        c.getApellidos(),
                        c.getDni(),
                        c.getEmail(),
                        genero
                    };
            tableModel.addRow(rowData);
        }
        tbl_clientes.setModel(tableModel);
        JOptionPane.showMessageDialog(null, "Carga Completada :) ", "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        btn_cargar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_añadir = new javax.swing.JButton();

        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Dni", "Email", "Genero"
            }
        ));
        tbl_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbl_clientes);

        btn_cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/cargando.png"))); // NOI18N
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/edit.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/delete.png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pe/recursos/img/mas.png"))); // NOI18N
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_editar))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cargar)
                .addGap(18, 18, 18)
                .addComponent(btn_añadir)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cargar)
                    .addComponent(btn_añadir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_editar)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {
          if (tbl_clientes.getRowCount() > 0) { //tabla no vacia
            if (tbl_clientes.getSelectedRow() != -1) {
                int idcliente = Integer.parseInt(tbl_clientes.getValueAt(tbl_clientes.getSelectedRow(), 0).toString());
                System.out.println("id_cliente: "+idcliente);
                EditarCliente ec = new EditarCliente(idcliente);
                ec.setSize(700, 500);
                ec.setLocation(0, 0);
                ec.setVisible(true);
                ec.setLocationRelativeTo(null);
            }
        }
        
    }

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {

       AgregarCliente a = new AgregarCliente();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        a.setSize(700, 500);
        a.setLocation(400,300);

        
    }

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {

     if (tbl_clientes.getRowCount() > 0) { //tabla no vacia
            if (tbl_clientes.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(tbl_clientes.getValueAt(tbl_clientes.getSelectedRow(), 0).toString());
                int resp = JOptionPane.showConfirmDialog(null, "Esta usted seguro de eliminar el cliente?");
                if (JOptionPane.OK_OPTION == resp) {
                    c.setIdcliente(idCliente);
                    CDao.eliminar(c);
                    JOptionPane.showMessageDialog(null, "usuario eliminado :( ", "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                    cargarClientes();
                } else {
                    JOptionPane.showMessageDialog(null, "Operación Cancelada :(", "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {
     cargarClientes();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_clientes;
    // End of variables declaration//GEN-END:variables
}
